workflows:
    react-native:
      name: react native
      environment:
        flutter: stable
      triggering:
        events:
          - push
        branch_patterns:
          - pattern: 'android_using_plugin_no_codesign'
            include: true
            source: true
      scripts:
        - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android_using_plugin/local.properties"
        - cd flutter_module_using_plugin && flutter pub get
        - cd android_using_plugin && ./gradlew build
      artifacts:
        - android_using_plugin/app/build/outputs/**/**/*.apk
