workflows:
    ios-prebuilt-flutter-module:
      name: ios_prebuilt_flutter_module
      environment:
        xcode: latest
        cocoapods: default
        flutter: stable
      triggering:
        events:
          - push
        branch_patterns:
          - pattern: 'ios_prebuilt_flutter_module_without_codesign'
            include: true
            source: true
      scripts:
        - |
          # build Flutter module
          cd flutter_module
          flutter packages get
          flutter build ios-framework --output=$FCI_BUILD_DIR/ios_using_prebuilt_module/Flutter
        - |
          # build iOS project
          cd ios_using_prebuilt_module
          pod install
          xcodebuild build -workspace "IOSUsingPrebuiltModule.xcworkspace" -scheme "IOSUsingPrebuiltModule" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      artifacts:
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
