workflows:
    ios-flutter-module:
      name: ios_flutter_module
      environment:
        xcode: latest
        cocoapods: default
        flutter: stable
      triggering:
        events:
          - push
        branch_patterns:
          - pattern: 'ios_flutter_module_no_codesign'
            include: true
            source: true
      scripts:
        - |
          cd flutter_module_using_plugin
          flutter pub get
          flutter build ios --release --no-codesign
          cd .ios && pod install
        - cd ios_using_plugin && pod deintegrate && pod install
        - cd ios_using_plugin && xcodebuild -workspace "IOSUsingPlugin.xcworkspace" -scheme "IOSUsingPlugin" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO build
      artifacts:
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
